#@NOTE:导出PDB文件
install(FILES $<TARGET_PDB_FILE:${PROJECT_NAME}>
    DESTINATION ${PROJECT_NAME}/${CMAKE_BUILD_TYPE}/lib OPTIONAL
)
#@NOTE:导出dll
install(TARGETS ${PROJECT_NAME}
    DESTINATION ${PROJECT_NAME}/${CMAKE_BUILD_TYPE}/lib/
    PUBLIC_HEADER DESTINATION ${PROJECT_NAME}/${CMAKE_BUILD_TYPE}/include/${PROJECT_NAME}/
)
#@NOTE:导出头文件
install(FILES ${EXPORT_HEADERS}
    DESTINATION ${PROJECT_NAME}/${CMAKE_BUILD_TYPE}/include/${PROJECT_NAME}/
)
#@NOTE:导出可执行文件到实例代码
install(TARGETS ${PROJECT_NAME}
    LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/ElaWidgetToolsExample/${CMAKE_BUILD_TYPE}
    RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/ElaWidgetToolsExample/${CMAKE_BUILD_TYPE}
)
